
def convertKey(button):
    PYNPUT_SPECIAL_CASE_MAP = {
        'alt_l': 'altleft',
        'alr_r': 'altright',
        'alt_gr': 'altright',
        'caps_lock': 'capslock',
        'ctrl_l': 'ctrlleft',
        'ctrl_r': 'ctrlright',
        'page_down': 'pagedown',
        'page_up': 'pageup',
        'shift_l': 'shiftleft',
        'shift_r': 'shiftright',
        'num_lock': 'numlock',
        'print_screen': 'printscreen',
        'scroll_lock': 'scrolllock',
        'Button.left': 'left',
        'Button.right': 'right',
        'Button.middle': 'middle',
        'Q': 'q',
        'W': 'w',
        'E': 'e',
        'R': 'r',
        'T': 't',
        'Y': 'y',
        'U': 'u',
        'I': 'i',
        'O': 'o',
        'P': 'p',
        'A': 'a',
        'S': 's',
        'D': 'd',
        'F': 'f',
        'G': 'g',
        'H': 'h',
        'J': 'j',
        'K': 'k',
        'L': 'l',
        'Z': 'z',
        'X': 'x',
        'C': 'c',
        'V': 'v',
        'B': 'b',
        'N': 'n',
        'M': 'm',
        '!': '1',
        '@': '2',
        '#': '3',
        '$': '4',
        '%': '5',
        '^': '6',
        '&': '7',
        '*': '8',
        '(': '9',
        ')': '0',
        '_': '-',
        '+': '=',
        '{': '[',
        '}': ']',
        '|': '\\',
        ':': ';',
        '"': '\'',
        '<': ',',
        '>': '.',
        '?': '/',
        '~': '`',
    }

    cleaned_key = button.replace('Key.', '')

    if cleaned_key in PYNPUT_SPECIAL_CASE_MAP:
        return PYNPUT_SPECIAL_CASE_MAP[cleaned_key]

    return cleaned_key
